development:
  server: "http://192.168.0.2:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://wiggler.nomelette.co.uk/faye"
  secret_token: "fcca483dc5bb219fb8ee252de517a2d674366e47103804bf3d30b93c11b39e5f"
  signature_expiration: 3600 # one hour
